name: food_ordering
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  dots_indicator: ^4.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
    - family: GreatVibes
      fonts:
        - asset: assets/font/GreatVibes-Regular.ttf
          weight: 300
  assets:
    - assets/images/
